package com.rsm.rsm_backend.entity;

public enum RequestStatus {
    WAITING_FOR_AN_EMAIL_VERIFICATION,
    WAITING_FOR_A_MECHANIC_ASSIGNMENT,
    WAITING_FOR_DATE_ASSIGNMENT,
    WAITING_FOR_A_CAR,
    CAR_DIAGNOSIS,
    IN_REPAIR,
    READY_TO_GO,
    DONE
}
